### ISSUE TITLE
The shape of pressure mean and std

### ISSUE THREAD

**Issue by labiao** [DeifiliaTo/PanguWeather#3]
Hi, thanks for your great work.
I'm trying to reproduce your code, but I got an error. The 'calculate_static_zarr_all.py' generates pressure mean and std with a shape of (5,1,1,1). However,  in 'data_loader_multifiles.py',
`self.p_mean = np.load(params['pressure_static_data_path'], allow_pickle=True)[0].reshape(5, 13, 1, 1)` 
`self.p_std  = np.load(params['pressure_static_data_path'], allow_pickle=True)[1].reshape(5, 13, 1, 1)`
It will raise a shapeerror: cannot reshape array of size 5 into shape (5, 13, 1, 1). 
Any help is appreciated.

**Comment by DeifiliaTo** [comment]
Apologies, that code was written for a previous experiment where the normalization was done across variables and not across individual pressure levels AND variables. 

I've made the appropriate changes in 'calculate_static_zarr_all.py', but you can also just change lines 16 & 17 of that file to:
`sample_pressure_mean = np.mean(sample_pressure, axis=(0, 3, 4)).reshape(5, 13, 1, 1)`
`sample_pressure_std  = np.std(sample_pressure, axis=(0, 3, 4)).reshape(5, 13, 1, 1)`
